eureka:
  client:
    healthcheck:
      enabled: false #true
    service-url:
      defaultZone: http://admin:admin@192.168.137.10:8761/eureka #http://peer1:8761/eureka,http://peer2:8762/eureka
    fetchRegistry: true
  instance:
    prefer-ip-address: true
    instanceId: ${spring.application.name}:${eureka.instance.ip-address}:${server.port}
    ip-address: 192.168.137.10
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  servlet:
    multipart:
      max-file-size: 256MB
      max-request-size: 1024MB