spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver #com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.137.10:3306/purchaseonline?useUnicode=true&characterEncoding=utf-8&transformedBitIsBoolean=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&autoReconnect=true&failOverReadOnly=false&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  redis:
    host: 192.168.137.10
  rabbitmq:
    host: 192.168.137.10
eureka:
  client:
    healthcheck:
      enabled: false #true
    service-url:
      defaultZone: http://admin:admin@192.168.137.10:8761/eureka #http://peer1:8761/eureka,http://peer2:8762/eureka
    fetchRegistry: true
  instance:
    prefer-ip-address: true
    instanceId: ${spring.application.name}:${eureka.instance.ip-address}:${server.port}
    ip-address: 192.168.137.10  #192.168.1.190
    #instanceId: ${spring.application.name}:${eureka.instance.hostname}:${server.port}
    #hostname: localhost
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
  hystrix:
    enabled: true