server:
  port: 8040
spring:
  security:
    user:
      name: admin
      password: admin
  mail:
    host: localhost
    port: 25
  boot:
    admin:
      notify:
        mail:
          to: ["zhilong.li1995@gmail.com"]
          cc: ["autoreply@puchaseonline.com"]
          from: noreply@localhost
          enabled: true
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    hostname: localhost
    prefer-ip-address: true
    metadata-map:
      user.name: ${spring.security.user.name}
      user.password: ${spring.security.user.password}
      startup: ${random.int}
    instance-id: ${spring.application.name}:${eureka.instance.hostname}:${server.port}
  client:
    # registryFetchIntervalSeconds: 5
    service-url:
      defaultZone: http://admin:admin@127.0.0.1:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
