server:
  port: 8042
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver #com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zhilong?useUnicode=true&characterEncoding=utf-8&transformedBitIsBoolean=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&autoReconnect=true&failOverReadOnly=false&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: root123
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
  redis:
    host: 192.168.137.10
eureka:
  client:
    healthcheck:
      enabled: true
    fetchRegistry: true 
    serviceUrl:
      defaultZone: http://admin:admin@localhost:8761/eureka #http://peer1:8761/eureka,http://peer2:8762/eureka
  instance:
    prefer-ip-address: true
    hostname: localhost
    instanceId: ${spring.application.name}:${eureka.instance.hostname}:${server.port}

#Extremely large files will also require elevated timeout settings 
#if the proxy route takes you through a Ribbon load balancer, e.g.
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000